googleinterns/step39-2020

capstone/client/package.json, capstone/client/src/components/ListPage.js, capstone/client/src/components/ListPage.test.js, capstone/client/yarn.lock
Manually added a hard-coded list of items. Will change this to use Items API once it is functional. 
The hard-coded list of items are used to create a checkbox list. When an item is checked, it is stored in the selectedItems set and when an item is unchecked, it is removed from the selectedItems set. When the submit button is pressed, the selected items are displayed underneath the checkbox list. 
The following gif shows the new functionality:
=> Implement checkbox list displays selected items below on submit.

capstone/client/src/components/ListPage.js, capstone/client/src/components/styles.css
Added the UI that allows the user to select a maximum distance preference for the recommended stores. The selected distance value is stored in the state. 
Added styling that uses a grid format to display the two selection lists side-by-side. Modified font and background colors. 
Edit: Added a save list button and a success alert. 
The following is a screenshot showing the changes:
=> Add UI for distance preference selection and change styling. 

capstone/backend/pom.xml, capstone/backend/src/main/java/com/google/spanner/CreateSpannerTables.java, capstone/backend/src/main/java/com/google/spanner/LibraryFunctions.java, capstone/backend/src/test/java/com/google/spanner/LibraryFunctionsTest.java
Used some of Anudeep's implementation to create a LibraryFunctions java class that allows API's to easily access results from the Spanner database, abstracting the Spanner functions into simple java native types like int, string, etc.
5 major functions:
- initClient (tested via getUserLists and getItemTypes)
- writeUserLists (untested)
- getUserLists (tested successfully)
- createUser (untested)
- getItemTypes (tested successfully)
Additionally, I created a tester file LibraryFunctionsTest.java that includes two tests for this java code that both run successfully.
Updated POM dependencies to allow for this.
Also changed the class name in CreateSpannerTables to allow for compilation. (ignored in previous PR)
=> Library functions

capstone/backend/src/main/java/com/google/servlets/CreateUserServlet.java, capstone/backend/src/test/java/com/google/CreateUserServletTest.java
Added a function that handles a POST request to "/api/v1/create-user". A userId is generated from the email address provided by the user and the user information is stored in the database. 
Added a test for a successful request and a request with invalid syntax.
=> Implement API endpoint to add a new user to the database. 

capstone/backend/pom.xml, capstone/backend/src/main/java/com/google/servlets/LoginServlet.java, capstone/backend/src/test/java/com/google/servlets/LoginServletTest.java
Added a servlet that handles a GET request to "/api/v1/login". The doGet() function responds with an object containing login information for the user. If the user isn't logged in, a login object is returned with the status set to false and a login URL. If the user is logged in, a login object is returned with the status set to true, the user's email address, and a logout URL.
Added one test that checks if LoginServlet works as expected when the user isn't logged in and one test that checks if LoginServlet works as expected when the user is logged in.
=> Add API endpoint that handles user login using the Users API.

capstone/backend/src/main/java/com/google/servlets/Item.java, capstone/backend/src/main/java/com/google/servlets/Store.java, capstone/backend/src/main/java/com/google/spanner/LibraryFunctions.java
In order to build out the functionality for a Library Function and an API that are able to take a users list of itemtypes and turn that into a list of stores with certain items and prices, I created Store and Item classes whose instance data match that of the API result described in the design doc
Store:
- Total Price
- Store ID
- Store Address
- Store Name
- List of Items
Item: 
- Item ID
- Item Price
- Item Name
I also added a constructor that is able to take another Store and some item information and create a new store with the added item. I think this will be useful when we are creating dozens of permutations of stores (i.e. one store has many different items and we want to provide the user with all of those permutations to pick from)
=> Added initial infrastructure for getStores functionality

capstone/backend/src/main/java/com/google/servlets/CreateOrUpdateUserlistServlet.java, capstone/backend/src/main/java/com/google/servlets/GetUserListsServlet.java, capstone/backend/src/test/java/com/google/servlets/CreateOrUpdateUserlistServletTest.java, capstone/backend/src/test/java/com/google/servlets/GetItemTypesServletTest.java, capstone/backend/src/test/java/com/google/servlets/GetUserListsServletTest.java
Modified tests so they use use mock LibraryFunctions for database operations meaning that the tests aren't reliant on specific data from the database.
=> Modify servlet tests so that they don't read and write from the actual database.

capstone/backend/src/main/java/com/google/servlets/CreateOrUpdateUserlistServlet.java, capstone/backend/src/main/java/com/google/servlets/CreateUserServlet.java, capstone/backend/src/main/java/com/google/servlets/DataServlet.java, capstone/backend/src/main/java/com/google/servlets/GetItemTypesServlet.java, capstone/backend/src/main/java/com/google/servlets/GetUserListsServlet.java, capstone/backend/src/main/java/com/google/servlets/Item.java, capstone/backend/src/main/java/com/google/servlets/ServletUtil.java, capstone/backend/src/main/java/com/google/servlets/Store.java, capstone/backend/src/main/java/com/google/servlets/UserList.java, capstone/backend/src/main/java/com/google/spanner/LibraryFunctions.java, capstone/backend/src/test/java/com/google/servlets/CreateOrUpdateUserlistServletTest.java, capstone/backend/src/test/java/com/google/servlets/CreateUserServletTest.java, capstone/backend/src/test/java/com/google/servlets/GetUserListsServletTest.java, capstone/backend/src/test/java/com/google/servlets/ServletTestUtil.java, capstone/backend/src/test/java/com/google/servlets/SetupObj.java, capstone/client/src/App.js, capstone/client/src/components/Header.js, capstone/client/src/components/ListPage.js, capstone/client/src/components/ListPage.test.js, capstone/client/src/components/Store.js, capstone/client/src/components/WebRouter.js, capstone/client/src/components/styles.css, makefile
Added Apache license comment to the files that we made changes to. Ran Java linter to fix styling and added a makefile with the script to run the linter. Also added a missing bracket in ListPage.js that was accidentally removed during a merge.
=> Add Apache License to each file and run Java linter.

capstone/backend/scraper/scraper.py, capstone/backend/scraper/test/scraper_test.py
=> Distinguish scraping of item information and inventory information.

capstone/client/src/components/Header.js, capstone/client/src/components/ListPage.js
Added comments to clarify what some of the functions do. Used the store.on().subscribe() function to update the userId in the state of the listPage when a user logs in.
=> Add comments and add functionality to save the userId in the state after a user logs in. 

capstone/backend/src/main/java/com/google/servlets/CreateUserServlet.java, capstone/backend/src/main/java/com/google/spanner/LibraryFunctions.java, capstone/backend/src/main/webapp/WEB-INF/appengine-web.xml, capstone/client/src/components/ListPage.js
Modified the projectId for the backend so it gets deployed properly. Fixed typos with the alert message and save lists POST request. Modified CreateUserServlet so an error isn't thrown if a user already exists (Maybe change the name to CreateOrFindUserServlet?) 
I deployed both the frontend and the backend to a live server which is accessible with the following link: https://step39-2020.uc.r.appspot.com/
The following is a gif shows some of the current functionality:
I manually checked the database after logging in and saving a list. A new user with the specified email and the saved list were both added to the database.
=> Fix minor bugs and deploy application to live server 

capstone/backend/src/test/java/com/google/spanner/LibraryFunctionsTest.java
Converted Library function test file to use the test database, where all of the data inside of it is inserted and deleted before and after the testing is done.
This allows for ease of use when trying to modify the testing data as well as makes it explicitly clear what the data is and where it exists when we encounter errors. This contrasts the current system of needing to go into the database and bounce back and forth between the Spanner UI and the code.
This code passes the tests multiple times over, verifying that it works in its job to insert and delete data.
=> test database and data

capstone/backend/src/main/java/com/google/servlets/Item.java, capstone/backend/src/main/java/com/google/servlets/Store.java, capstone/backend/src/main/java/com/google/spanner/LibraryFunctions.java, capstone/backend/src/test/java/com/google/spanner/LibraryFunctionsTest.java
Updated the Library Functions code as well as the Store and Item objects to be conducive to the changing of the Inventory name to Inventories, ItemNameAndBrand divided into ItemName and ItemBrand, and finally the ItemId changing to a String from a long
=> fixed for new database schema, passes all tests

capstone/backend/scraper/cron.py
Properly set up! 
You can also use crontab -e on the command line to set up the cron job.
=> Set up a cron job for scraper.

capstone/backend/scraper/scraper.py, capstone/client/src/components/ListPage.js
The request is hard-coded to show only the first page of item types for now (will do more pages in next pull request).
Right now, the checkbox list looks like:
=> Get item types from database and display as options.

capstone/backend/pom.xml, capstone/backend/src/main/java/com/google/servlets/GetItemTypesServlet.java, capstone/backend/src/main/java/com/google/spanner/LibraryFunctions.java, capstone/backend/src/test/java/com/google/servlets/CreateUserServletTest.java, capstone/backend/src/test/java/com/google/servlets/GetItemTypesServletTest.java, capstone/backend/src/test/java/com/google/spanner/LibraryFunctionsTest.java, capstone/client/src/components/ListPage.js
This is easier than handling the requests on the front-end side. 
All tests pass.
=> Add an API function to get all item types (as opposed to a page by page basis).

capstone/client/src/components/ListPage.js, capstone/client/src/components/ListPage.test.js
The tests fail when you leave the navigator code in componentWillMount in, but otherwise, everything passes!
=> Adjust the tests for getItemTypes and add a new test.

capstone/client/src/components/StoreDetailCards.js, capstone/client/src/components/StoresPage.js
Wrote this code to work with hard-coded data, since the APIs are being changed. Resolved some of the warnings.
I'm also getting the following warning: "Warning: Can't call setState on a component that is not yet mounted. This is a no-op, but it might indicate a bug in your application. Instead, assign to `this.state` directly or define a `state = {};` class property with the desired state in the Wrapper component." Not sure what's wrong?
=> Show the correct information on the StoreDetails page.

capstone/client/src/components/Header.js, capstone/client/src/components/WebRouter.js
Modified the header to display the current page name on the top left.
=> Header displays the current page name on the top left.

capstone/client/src/components/FilterStores.js, capstone/client/src/components/StoresPage.js
Filters are all fixed such that they match the data
=> fixed filters

capstone/client/src/components/StoresPage.js, capstone/client/src/components/styles.css
Made a button that takes the user back to the list page
=> Back button

capstone/backend/src/main/java/com/google/servlets/GetStoreRankingsServlet.java, capstone/backend/src/main/java/com/google/servlets/Store.java, capstone/backend/src/main/java/com/google/spanner/LibraryFunctions.java, capstone/backend/src/test/java/com/google/servlets/GetStoreRankingsServletTest.java
Changes:
- modify to user insertOrUpdateBuilder instead of insertBuilder to fix bug with the createUser servlet.
- fix lowest potential price to be accurate
- reverse the sort of store ranking algorithm so stores higher ranked stores appear first
=> Bug fixes with store ranking and total price

capstone/client/src/components/StoreDetailCards.js, capstone/client/src/components/StoreMaps.js, capstone/client/src/components/StoresPage.js
=> Add store markers and center the maps accordingly.

capstone/client/package.json, capstone/client/src/components/ListPage.js, capstone/client/src/components/StoresPage.js, capstone/client/src/components/styles.css
Added functionality to enter zip code if the user blocks their location from the website.
If the user enters an invalid zip code and attempts to submit, the website will produce an error and refuse to submit
If they enter a normal Zip Code it works completely, please notice the difference in the lat and lon in the URL parameters
NEW EDITS =============================================================
=====================================================================
======================================================================
Further development of the Zip Code function makes it show up always, if a user allows location and doesnt enter a zipcode/enters an invalid one, it will just use their location. If they enter a valid zip code, it will override the location we track them …
=> Added Zip Code Functionality

capstone/client/src/components/StoreMaps.js, capstone/client/src/components/StoresPage.js
Also, fix a merge issue with the back button.
=> Update map marker when stores change.

capstone/client/src/components/FilterStores.js, capstone/client/src/components/ListPage.js, capstone/client/src/components/StoresPage.js, capstone/client/src/components/styles.css
Added a filter that allows the user to filter through the stores based on price using both a slider as well as a text input
The slider and text input adapt the the maximum cost of the original stores, and the standard step allotted for the text input (when you hover over the text input there is an arrow up and arrow down button) is the maximum price divided by 10.
EDIT: Made it so that if you only pass one item type the filter for items will not show up at all
--------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ …
=> Added price filter

capstone/client/src/components/StoreMaps.js, capstone/client/src/components/StoresPage.js
Also resized the column of Store Overviews to be less wide.
=> Resize the map to remove the right scrollable bug. 

capstone/client/src/components/FilterStores.js, capstone/client/src/components/StoreDetailCards.js, capstone/client/src/components/StoreMaps.js
Created a google maps URI that redirects the user to a google maps page with the destination pre-filled to be the store address. 
Also fixed the price filter to show the correct max price.
The following is a gif showing the functionality:
=> Add a get directions buttons that redirects to a page that displays directions to the specified store. 

capstone/client/src/components/ListPage.js, capstone/client/src/components/styles.css
Changes:
- Modified zipcode error so it is no longer displayed on page load
- Moved the distance preference of none to the top and made it the default selected value
- Fixed the title margins so there is less gap underneath the title 
The following is a screenshot showing the changes:
=> Remove zipcode error and modify distance preferences.

capstone/client/src/components/FilterStores.js
Made it so that the step is rounded to two decimal places
=> Rounding the step

capstone/client/src/components/FilterStores.js, capstone/client/src/components/styles.css
Implemented a filter for distance that mirrors the filter for price in terms of being two sided and allowing the user to enter min and max, it has a step of 1 mile.
=> Created Distance Filter

capstone/client/package.json, capstone/client/src/components/WebRouter.js, capstone/client/src/components/WelcomePage.js, capstone/client/src/components/styles.css
=> Add placeholder text, footer, and images to Welcome.

capstone/backend/src/main/java/com/google/servlets/RemoveUserlistServlet.java, capstone/backend/src/main/java/com/google/spanner/LibraryFunctions.java, capstone/backend/src/test/java/com/google/servlets/RemoveUserlistServletTest.java, capstone/client/src/components/ItemsList.js, capstone/client/src/components/ListPage.js, capstone/client/src/components/styles.css
Added a spanner util function that takes user id and list id and removes a user list form the spanner database. Implemented a servlet that handles a GET request to "/api/v1/remove-user-list" where it takes user id and list id as params and calls the library function deleteUserList() to remove a user list. Also added a test for this servlet. 
Implemented the frontend UI for removing a user list. The delete option appears if the user is logged in and has selected a new list. 
The following is a a gif showing the new feature:
=> Implement backend and frontend for removing user lists

capstone/client/src/components/StoresPage.js
Altered the back button so it goes back to the item selection page and not the welcome page
=> fixed back button

capstone/client/src/components/FilterStores.js, capstone/client/src/components/StoreDetailCards.js, capstone/client/src/components/StoreMaps.js, capstone/client/src/components/StoreOverviewCards.js, capstone/client/src/components/StoresPage.js, capstone/client/src/components/styles.css
Updated stores page to match our new color scheme
Also modified it so that the items have images, added icon for directions
=> updated button styles

capstone/backend/pom.xml, capstone/backend/src/main/java/com/google/servlets/ShareViaEmailServlet.java, capstone/backend/src/main/java/com/google/servlets/Store.java, capstone/backend/src/test/java/com/google/servlets/ShareViaEmailServletTest.java
Fixed email backend to be able to send emails from an appspot email address.
Also altered the backend so that instead of taking raw HTML it takes information from the user like latitude, longitude, itemTypes, and all of the stores to construct server-side HTML that is placed inside of the email.
=> Fixed Email Backend

capstone/client/src/components/styles.css
The following screenshots show the pages with the new buttons:
=> Change button colors for consistency and make button text lowercase to adhere to the style guide.

capstone/client/src/components/ItemsList.js, capstone/client/src/components/ListPage.js, capstone/client/src/components/StoreOverviewCards.js, capstone/client/src/components/StoresPage.js, capstone/client/src/components/WelcomePage.js
Added profile pic and description about myself to the welcome page. Also made some minor changes to fix the eslint warnings.
=> Add profile picture and description to welcome page

capstone/client/src/components/FilterStores.js, capstone/client/src/components/Header.js, capstone/client/src/components/ItemsList.js, capstone/client/src/components/StoreDetailCards.js, capstone/client/src/components/StoreOverviewCards.js, capstone/client/src/components/StoresPage.js, capstone/client/src/components/WelcomePage.js
For StoreOverviewCards, just adjusted indentation.
=> Add accessibility features, like aria labels.
